export let things = {
  room: {
    image: "room",
    x: 0,
    y: 0,
    scale: 4.5,
    depth: -9999,
    hitboxes: [
      {
        x: -42,
        y: -92,
        w: 1,
        h: 88,
        type: "solid",
      },
      {
        x: -41,
        y: -49,
        w: 34,
        h: 1,
        type: "solid",
      },
      {
        x: -20,
        y: -60,
        w: 31,
        h: 1,
        type: "solid",
      },
      {
        x: -8,
        y: -78,
        w: 1,
        h: 18,
        type: "solid",
      },
      {
        x: -31,
        y: -23,
        w: 42,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -34,
        w: 1,
        h: 21,
        type: "solid",
      },
      {
        x: -41,
        y: -92,
        w: 86,
        h: 1,
        type: "solid",
      },
      {
        x: 45,
        y: -92,
        w: 1,
        h: 88,
        type: "solid",
      },
      {
        x: -41,
        y: -5,
        w: 86,
        h: 1,
        type: "solid",
      },
      {
        x: 21,
        y: -71,
        w: 1,
        h: 44,
        type: "solid",
      },
      {
        x: 32,
        y: -72,
        w: 1,
        h: 4,
        type: "solid",
      },
      {
        x: 33,
        y: -68,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 34,
        y: -61,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 35,
        y: -54,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 36,
        y: -47,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 37,
        y: -40,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 38,
        y: -33,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 39,
        y: -26,
        w: 1,
        h: 7,
        type: "solid",
      },
      {
        x: 40,
        y: -19,
        w: 1,
        h: 4,
        type: "solid",
      },
      {
        x: 11,
        y: -61,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 12,
        y: -62,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 13,
        y: -63,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 14,
        y: -64,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 15,
        y: -65,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 16,
        y: -66,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 17,
        y: -67,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 18,
        y: -68,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 19,
        y: -69,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 20,
        y: -70,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -8,
        y: -24,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -7,
        y: -25,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -6,
        y: -26,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -5,
        y: -27,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -4,
        y: -27.9,
        w: 1,
        h: 0.8999999999999986,
        type: "solid",
      },
      {
        x: -3,
        y: -29,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -2,
        y: -30,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: -1,
        y: -31,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 0,
        y: -32,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 1,
        y: -33,
        w: 1,
        h: 1,
        type: "solid",
      },
      {
        x: 2,
        y: -34,
        w: 1,
        h: 1,
        type: "solid",
      },
    ],
  },
  thing: {
    image: "thing",
    x: -147,
    y: -362,
    scale: 1.3,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing1: {
    image: "thing",
    x: 172,
    y: -353,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing2: {
    image: "thing",
    x: 51,
    y: -330,
    scale: 3.2,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing3: {
    image: "thing",
    x: -61,
    y: -318,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing4: {
    image: "thing",
    x: 66,
    y: -274,
    scale: 1.3,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing5: {
    image: "thing",
    x: -130,
    y: -270,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing6: {
    image: "thing",
    x: 10,
    y: -195,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing7: {
    image: "thing",
    x: -131,
    y: -151,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing8: {
    image: "thing",
    x: -77,
    y: -150,
    scale: 0.35000000000000003,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing9: {
    image: "thing",
    x: 42,
    y: -58,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing10: {
    image: "thing",
    x: 139,
    y: -47,
    scale: 3.2,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
  thing11: {
    image: "thing",
    x: -153,
    y: -33,
    scale: 1,
    interact: pickUp,
    hitboxes: [
      {
        x: -8,
        y: -1,
        w: 16,
        h: 1,
        type: "solid",
      },
      {
        x: -9,
        y: -17,
        w: 18,
        h: 17,
        type: "trigger",
      },
    ],
  },
};

function pickUp(self) {
  self.zones.forEach((zone) => {
    zone.destroy();
  });
  self.destroy();
  window.ui.write("picked up " + self.name, 2000);
  console.log(self.name);
}
